services:
  - type: web
    name: healthcare-ai-backend
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
